spring:
  main:
    web-application-type: reactive
  application:
  name: truproxyapi
  data:
    mongodb:
      host:
        port: 27017
      uri: mongodb://localhost:27017/truproxy
#debug: true
proxy:
#  endpoint: "http://localhost:1080"
  endpoint: "https://exercise.trunarrative.cloud/TruProxyAPI/rest/Companies/v1"
  apiKey: ${API_KEY}
  apiValue: ${API_KEY_VALUE}

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              ReactiveMongoTemplate: DEBUG